name: uni_links
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.6.6
homepage: https://github.com/ProsBucket/prosbucket-app-uni-links/tree/main/uni_links

dependencies:
  flutter:
    sdk: flutter
  uni_links_platform_interface: ^1.0.0
  uni_links_web: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.0.0'
  flutter: ^3.10.1

flutter:
  plugin:
    platforms:
      android:
        package: com.prosbucket.unilinks
        pluginClass: UniLinksPlugin
      ios:
        pluginClass: UniLinksPlugin
      web:
        default_package: uni_links_web
